spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test-db
    username: test
    password:
