server:
  port: 8090

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test-db
    username: test
    password:

  output:
    ansi:
      enabled: always

logging.pattern.console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint}%replace( [%X{txid}]){' \\[\\]', ''} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
